In [1]:
import torch

In [2]:
x=torch.tensor([1,2,3,4,5])

In [3]:
y=torch.tensor([[[1,2],[3,4]]])

In [4]:
print(y)

tensor([[[1, 2],
         [3, 4]]])


In [5]:
z=torch.zeros(4,4)

In [6]:
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
o=torch.ones(2,3)

In [8]:
o

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
r=torch.rand(3,2)
r

tensor([[0.4876, 0.7579],
        [0.1616, 0.2484],
        [0.7771, 0.9341]])

In [10]:
r.shape

torch.Size([3, 2])